@baseUrl = http://localhost:3333
@accessToken = {{autenthenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "password": "123123"
}

###

# @name autenthenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "123123"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "My new question",
  "content": "How magnets really work?"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Authorization: Bearer {{accessToken}}
